# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eltOoL0vmdrWJpSuFIfEoJlubDEbY9Uo
"""

###Task 1
#I used colab for doing all the codes
from numpy import True_

#Function for Palindrome
def isPalindrome(word):
  if word == "":
    return "not palindrome"
  else:
    n = len(word)
    for i in range(int(n/2)):
      if word[i] != word[n-1-i]:
        return "not palindrome"
    return "palindrome"

#Function for Parity Check
def isEven(num):
  if num %2 == 0:
    return True
  elif num %2 != 1:
    return False
  else:
    return 0

#accessing input from input file
file1 = open('input.txt')
lines = file1.readlines()

#creating 2 lists of equal length, which will show whether the number or word meet the required criteria
parityStat = [0]*len(lines) 
palindromeStat = [0]*len(lines)

#updating the lists..
n = 0
i = 0
for line in lines:
  x = line.split()
  if x[0].isdigit():
    t = int(x[0])
    if isEven(t) == True:
      parityStat[n] += 2
    elif isEven(t) == False:
      parityStat[n] += 1
  n += 1
  
  if isPalindrome(x[1]) == "palindrome":
    palindromeStat[i] += 1
  i += 1
  
#calculations for the record file
e = parityStat.count(2)
o = parityStat.count(1)
p = palindromeStat.count(1)
evenParity = int((e/len(lines))*100)
oddParity = int((o/len(lines))*100)
noParity = 100 - (evenParity+oddParity)
palindrome = int(p/len(lines)*100)
notPal = 100 - palindrome

file2 = open("record.txt", mode = "w")
str1 = f"Percentage of odd parity: {oddParity}%\n"
str2 = f"Percentage of even parity: {evenParity}% \n"
str3 = f"Percentage of no parity: {noParity}%\n"
str4 = f"Percentage of palindrome: {palindrome}%\n"
str5 = f"Percentage of non palindrome: {notPal}%\n"
file2.writelines([str1,str2,str3,str4,str5])
file2.close()

#converting the digits from status list to words to help in output
#i think this was a very weird way to do this problem :3

for i in range(len(palindromeStat)):
  if palindromeStat[i] == 1:
    palindromeStat[i] = 'is a palindrome'
  else:
    palindromeStat[i] = 'is not a palindrome'

for i in range(len(parityStat)):
  if parityStat[i] == 2:
    parityStat[i] = "has even parity"
  elif parityStat[i] == 1:
    parityStat[i] = "has odd parity"
  else:
    parityStat[i] = "cannot have parity"


#accessing and writing the output file
file3 = open('output.txt', mode = 'w')

result = []
i = 0
for line in lines:
  x = line.split()
  file3.write(f"{x[0]} {parityStat[i]} and {x[1]} {palindromeStat[i]}\n")
  i += 1
file3.close()
print(parityStat)